name: NPM Package (Bun)

on:
  release:
    types: [created]  # Triggers only when a release is created

jobs:
  build-and-publish:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest
          registry-url: https://registry.npmjs.org/

      - run: bun install --frozen-lockfile
      - run: bun test

      - name: Publish to npm
        run: bun publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}